title: Bence Hamrak 
logo: https://dsps.ceu.edu/sites/pds.ceu.hu/files/styles/panopoly_image_full/public/profilephd/portrait/1460/profile.jpg?itok=GsDjZKNG
description: ðŸ¦‹ <a href="https://bsky.app/profile/benhmrk.bsky.social"> <@benhmrk.bsky.social> </a> âœ‰ï¸ hamrak_bence@phd.ceu.edu>
theme: jekyll-theme-minimal
show_downloads: false
