title: Bence Hamrak 
logo: 
description: > 
  âœ‰ï¸ <a href="mailto:hamrak_bence@phd.ceu.edu"> hamrak_bence@phd.ceu.edu </a> 
  <br>
  ğŸ¦‹ <a href="https://bsky.app/profile/benhmrk.bsky.social"> @benhmrk.bsky.social </a> 
  <br>
  ğŸ“ <a href="https://scholar.google.com/citations?user=uOswV2gAAAAJ&hl=hu"> Google scholar </a>
  <br>
  ğŸ’¼ <a href="https://www.linkedin.com/in/bence-hamrak-b2010a133/"> LinkedIn </a>
  <br>
  ğŸ“ <a href=""> Cirruculum vitae </a>
theme: jekyll-theme-minimal
show_downloads: false
github:
  is_project_page: false
  is_user_page: false
