title: Bence HamrÃ¡k 
logo: /logo.jpeg
description: > 
  <br>
  âœ‰ï¸ <a href="mailto:hamrak_bence@phd.ceu.edu"> hamrak_bence@phd.ceu.edu </a> 
  <br>
  ğŸ¦‹ <a href="https://bsky.app/profile/benhmrk.bsky.social"> @benhmrk.bsky.social </a> 
  <br>
  ğŸ“ <a href="https://scholar.google.com/citations?user=uOswV2gAAAAJ&hl=hu"> Google scholar </a>
  <br>
  ğŸ’¼ <a href="https://www.linkedin.com/in/bence-hamrak-b2010a133/"> LinkedIn </a>
  <br>
  ğŸ“ <a href="https://drive.google.com/file/d/1_W7oUG6iLJaVySmY5LIPaF_THFYthBT1/view?usp=share_link"> Cirruculum vitae </a>
theme: jekyll-theme-minimal
sass: 
  custom_css: /assets/css/style.scss
show_downloads: false
github:
  is_project_page: false
  is_user_page: false
