title: Bence HamrÃ¡k 
logo: /assets/icons/logo.jpeg
description: > 
  <br>
  âœ‰ï¸ <a href="mailto:hamrak_bence@phd.ceu.edu"> hamrak_bence@phd.ceu.edu </a> 
  <br>
  ğŸ¦‹ <a href="https://bsky.app/profile/bencehamrak.bsky.social"> @benhmrk.bsky.social </a> 
  <br>
  ğŸ“ <a href="https://scholar.google.com/citations?user=uOswV2gAAAAJ&hl=hu"> Google scholar </a>
  <br>
theme: jekyll-theme-minimal
sass: 
  custom_css: /assets/css/style.scss
show_downloads: false
github:
  is_project_page: false
  is_user_page: false
